In [1]:
print("yo")
print("oh no")

yo
oh no

## Utils

In [2]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in a:\6 kod\kth-kurser\dlfk ht25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages (0.14.0)
Requirement already satisfied: numpy<3,>=1.25.2 in a:\6 kod\kth-kurser\dlfk ht25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages (from imbalanced-learn) (2.2.6)
Requirement already satisfied: scipy<2,>=1.11.4 in a:\6 kod\kth-kurser\dlfk ht25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages (from imbalanced-learn) (1.15.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in a:\6 kod\kth-kurser\dlfk ht25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages (from imbalanced-learn) (1.7.2)
Requirement already satisfied: joblib<2,>=1.2.0 in a:\6 kod\kth-kurser\dlfk ht25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages (from imbalanced-learn) (1.5.2)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in a:\6 kod\kth-kurser\dlfk ht25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages (from imbalanced-learn) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# Source - https://stackoverflow.com/a
# Posted by Afshin Amiri, modified by community. See post 'Timeline' for change history
# Retrieved 2025-11-17, License - CC BY-SA 4.0

# ---- RUN THIS TO UNZIP FOLDER ----
#import zipfile as zf
#files = zf.ZipFile("datasets.zip", 'r')
#files.extractall('./')
#files.close()

# Data

In [4]:


import numpy as np
import os.path
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [5]:
data_dict = {}

## Abalone-17_vs_7-8-9-10 dataset

### Prepare data

In [6]:
file_name = "./datasets/abalone-17_vs_7-8-9-10/abalone-17_vs_7-8-9-10.dat"
#if os.path.exists(file_name):
#    print("exists")

df = pd.read_csv(
    file_name,
    comment='@',
    header=None,
    sep=','
)

columns = [
    "Sex", "Length", "Diameter", "Height",
    "Whole_weight", "Shucked_weight",
    "Viscera_weight", "Shell_weight",
    "Class"
]

df.columns = columns

df = pd.get_dummies(df, columns=["Sex"], dtype=int)

# print(df["Class"].unique())
df["Class"] = df["Class"].map({" negative": 0, " positive": 1})

X = df.drop("Class", axis=1).values
y = df["Class"].values

df

#folds = load_data(file_name, type_data="imbalanced", raw=True)

,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Class,Sex_F,Sex_I,Sex_M
0,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,0,0,0,1
1,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,0,0,1,0
2,0.355,0.280,0.085,0.2905,0.0950,0.0395,0.115,0,0,1,0
3,0.365,0.295,0.080,0.2555,0.0970,0.0430,0.100,0,0,0,1
4,0.390,0.295,0.095,0.2030,0.0875,0.0450,0.075,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
2333,0.570,0.440,0.140,0.9535,0.3785,0.2010,0.305,1,1,0,0
2334,0.585,0.455,0.125,1.0270,0.3910,0.2120,0.250,1,0,0,1
2335,0.620,0.485,0.220,1.5110,0.5095,0.2840,0.510,1,1,0,0
2336,0.635,0.505,0.185,1.3035,0.5010,0.2950,0.410,1,1,0,0
2337,0.540,0.435,0.145,0.9700,0.4285,0.2200,0.264,1,0,1,0

### Data cleaning

In [7]:
X = df.drop(columns=["Class", "Sex_F", "Sex_I", "Sex_M"], errors='ignore').values
y = df["Class"].values

count_class = df["Class"].value_counts()

imb_count = df["Class"].value_counts(normalize=True) * 100
imb_count

imb_ratio = count_class.max() / count_class.min()
imb_ratio

data_dict['abalone-17_vs_7-8-9-10'] = (X, y, imb_ratio, imb_count)
print(data_dict['abalone-17_vs_7-8-9-10'])

(array([[0.35  , 0.265 , 0.09  , ..., 0.0995, 0.0485, 0.07  ],
       [0.33  , 0.255 , 0.08  , ..., 0.0895, 0.0395, 0.055 ],
       [0.355 , 0.28  , 0.085 , ..., 0.095 , 0.0395, 0.115 ],
       ...,
       [0.62  , 0.485 , 0.22  , ..., 0.5095, 0.284 , 0.51  ],
       [0.635 , 0.505 , 0.185 , ..., 0.501 , 0.295 , 0.41  ],
       [0.54  , 0.435 , 0.145 , ..., 0.4285, 0.22  , 0.264 ]],
      shape=(2338, 7)), array([0, 0, 0, ..., 1, 1, 1], shape=(2338,)), np.float64(39.310344827586206), Class
0    97.519247
1     2.480753
Name: proportion, dtype: float64)

In [8]:
print(1/data_dict["abalone-17_vs_7-8-9-10"][2])

0.02543859649122807

## ecoli1 dataset

In [9]:
file_name = "./datasets/ecoli1/ecoli1.dat"
#if os.path.exists(file_name):
#    print("exists")

df = pd.read_csv(
    file_name,
    comment='@',
    header=None,
    sep=','
)

columns = [
    "Mcg", "Gvh", "Lip", "Chg",
    "Aac", "Alm1", "Alm2", "Class"
]

df.columns = columns

# set Class values to 0 and 1 but match even if trailing spaces after "positive" and "negative"

df["Class"] = df["Class"].map({" negative": 0, " positive": 1, " negative    ": 0})

X = df.drop("Class", axis=1).values
y = df["Class"].values

df

#folds = load_data(file_name, type_data="imbalanced", raw=True)

      Mcg   Gvh   Lip  Chg   Aac  Alm1  Alm2  Class
0    0.49  0.29  0.48  0.5  0.56  0.24  0.35      0
1    0.07  0.40  0.48  0.5  0.54  0.35  0.44      0
2    0.56  0.40  0.48  0.5  0.49  0.37  0.46      0
3    0.59  0.49  0.48  0.5  0.52  0.45  0.36      0
4    0.23  0.32  0.48  0.5  0.55  0.25  0.35      0
..    ...   ...   ...  ...   ...   ...   ...    ...
331  0.74  0.56  0.48  0.5  0.47  0.68  0.30      0
332  0.71  0.57  0.48  0.5  0.48  0.35  0.32      0
333  0.61  0.60  0.48  0.5  0.44  0.39  0.38      0
334  0.59  0.61  0.48  0.5  0.42  0.42  0.37      0
335  0.74  0.74  0.48  0.5  0.31  0.53  0.52      0

[336 rows x 8 columns]

In [10]:
X = df.drop(columns=["Class"], errors='ignore').values # Note that there are a few NaNs after defining df so errors ignore is needed, gives a slightly different imbalance ratio
y = df["Class"].values

count_class = df["Class"].value_counts()

imb_count = df["Class"].value_counts(normalize=True) * 100
imb_count

imb_ratio = count_class.max() / count_class.min()
imb_ratio

data_dict['ecoli1'] = (X, y, imb_ratio, imb_count)
print(data_dict['ecoli1'])

(array([[0.49, 0.29, 0.48, ..., 0.56, 0.24, 0.35],
       [0.07, 0.4 , 0.48, ..., 0.54, 0.35, 0.44],
       [0.56, 0.4 , 0.48, ..., 0.49, 0.37, 0.46],
       ...,
       [0.61, 0.6 , 0.48, ..., 0.44, 0.39, 0.38],
       [0.59, 0.61, 0.48, ..., 0.42, 0.42, 0.37],
       [0.74, 0.74, 0.48, ..., 0.31, 0.53, 0.52]], shape=(336, 7)), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0]), np.float64(3.3636363636363638), Class
0    77.083333
1    22.916667
Name: proportion, dtype: float64)

## flare-F dataset - skipped because all is categorical and they claim they remove categorical... So we don't know what they did here.

In [11]:
# file_name = "./flare-F/flare-F.dat"
# #if os.path.exists(file_name):
# #    print("exists")

# df = pd.read_csv(
#     file_name,
#     comment='@',
#     header=None,
#     sep=','
# )

# columns = [
#     "LargestSpotSize", "SpotDistribution", "Activity", "Evolution", "Prev24Hour", "HistComplex", "BecomeHist", "Area", "C-class", "M-class", "X-class", "Class"
# ]

# df.columns = columns

# # print(df["Class"].unique())
# df["Class"] = df["Class"].map({" negative": 0, " positive": 1})

# X = df.drop("Class", axis=1).values
# y = df["Class"].values

# df

# #folds = load_data(file_name, type_data="imbalanced", raw=True)

## glass0 Dataset

In [12]:
file_name = "./datasets/glass0/glass0.dat"
#if os.path.exists(file_name):
#    print("exists")

df = pd.read_csv(
    file_name,
    comment='@',
    header=None,
    sep=','
)

columns = [
    "RI", "Na", "Mg", "Al", "Si", "K", "Ca", "Ba", "Fe", "Class"
]

df.columns = columns

# print(df["Class"].unique())
df["Class"] = df["Class"].map({" negative": 0, " positive": 1})

X = df.drop("Class", axis=1).values
y = df["Class"].values

df

#folds = load_data(file_name, type_data="imbalanced", raw=True)

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Class
0,1.515888,12.87795,3.43036,1.40066,73.2820,0.68931,8.04468,0.00000,0.1224,1
1,1.517642,12.97770,3.53812,1.21127,73.0020,0.65205,8.52888,0.00000,0.0000,1
2,1.522130,14.20795,3.82099,0.46976,71.7700,0.11178,9.57260,0.00000,0.0000,1
3,1.522221,13.21045,3.77160,0.79076,71.9884,0.13041,10.24520,0.00000,0.0000,1
4,1.517551,13.39000,3.65935,1.18880,72.7892,0.57132,8.27064,0.00000,0.0561,1
...,...,...,...,...,...,...,...,...,...,...
209,1.517278,14.70005,0.00000,2.34119,73.2820,0.00000,8.94852,0.66150,0.0000,0
210,1.516230,14.14145,0.00000,2.88047,72.6100,0.08073,9.18524,1.06155,0.0000,0
211,1.518371,14.32100,3.25974,2.21921,71.2492,1.45935,5.78508,1.62855,0.0000,0
212,1.516572,14.79980,0.00000,1.99130,73.1084,0.00000,8.28140,1.71045,0.0000,0
213,1.517323,14.95275,0.00000,1.79870,72.9908,0.00000,8.61496,1.54980,0.0000,0

In [13]:
X = df.drop(columns=["Class"], errors='ignore').values # Note that there are a few NaNs after defining df so errors ignore is needed, gives a slightly different imbalance ratio
y = df["Class"].values

count_class = df["Class"].value_counts()

imb_count = df["Class"].value_counts(normalize=True) * 100
imb_count

imb_ratio = count_class.max() / count_class.min()
imb_ratio

data_dict['glass0'] = (X, y, imb_ratio, imb_count)
print(data_dict['glass0'])

(array([[ 1.51588824, 12.87795   ,  3.43036   , ...,  8.04468   ,
         0.        ,  0.1224    ],
       [ 1.5176423 , 12.9777    ,  3.53812   , ...,  8.52888   ,
         0.        ,  0.        ],
       [ 1.52212996, 14.20795   ,  3.82099   , ...,  9.5726    ,
         0.        ,  0.        ],
       ...,
       [ 1.51837126, 14.321     ,  3.25974   , ...,  5.78508   ,
         1.62855   ,  0.        ],
       [ 1.51657164, 14.7998    ,  0.        , ...,  8.2814    ,
         1.71045   ,  0.        ],
       [ 1.51732338, 14.95275   ,  0.        , ...,  8.61496   ,
         1.5498    ,  0.        ]], shape=(214, 9)), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), np.float64(2.057142857142857), Class
0    67.28972
1    32.71028
Name: proportion, dtype: float64)

## vehicle1 Dataset - *This one only has integer valued data*

In [14]:
file_name = "./datasets/vehicle1/vehicle1.dat"
#if os.path.exists(file_name):
#    print("exists")

df = pd.read_csv(
    file_name,
    comment='@',
    header=None,
    sep=','
)

columns = [
    "Compactness", 
    "Circularity", 
    "Distance_circularity", 
    "Radius_ratio", 
    "Praxis_aspect_ratio", 
    "Max_length_aspect_ratio", 
    "Scatter_ratio", 
    "Elongatedness", 
    "Praxis_rectangular", 
    "Length_rectangular", 
    "Major_variance", 
    "Minor_variance", 
    "Gyration_radius", 
    "Major_skewness", 
    "Minor_skewness", 
    "Minor_kurtosis", 
    "Major_kurtosis", 
    "Hollows_ratio", 
    "Class"
]

df.columns = columns

# print(df["Class"].unique())
df["Class"] = df["Class"].map({" negative": 0, " positive": 1, " positive ": 1, " negative ": 0})

X = df.drop("Class", axis=1).values
y = df["Class"].values

df

#folds = load_data(file_name, type_data="imbalanced", raw=True)

,Compactness,Circularity,Distance_circularity,Radius_ratio,Praxis_aspect_ratio,Max_length_aspect_ratio,Scatter_ratio,Elongatedness,Praxis_rectangular,Length_rectangular,Major_variance,Minor_variance,Gyration_radius,Major_skewness,Minor_skewness,Minor_kurtosis,Major_kurtosis,Hollows_ratio,Class
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,0
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,0
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,1
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,0
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,93,39,87,183,64,8,169,40,20,134,200,422,149,72,7,25,188,195,1
842,89,46,84,163,66,11,159,43,20,159,173,368,176,72,1,20,186,197,0
843,106,54,101,222,67,12,222,30,25,173,228,721,200,70,3,4,187,201,1
844,86,36,78,146,58,7,135,50,18,124,155,270,148,66,0,25,190,195,1
845,85,36,66,123,55,5,120,56,17,128,140,212,131,73,1,18,186,190,0

In [15]:
X = df.drop(columns=["Class"], errors='ignore').values 
y = df["Class"].values

count_class = df["Class"].value_counts()

imb_count = df["Class"].value_counts(normalize=True) * 100
imb_count

imb_ratio = count_class.max() / count_class.min()
print(imb_ratio)

data_dict['vehicle1'] = (X, y, imb_ratio, imb_count)
print(data_dict['vehicle1'])

2.8986175115207375
(array([[ 95,  48,  83, ...,  16, 187, 197],
       [ 91,  41,  84, ...,  14, 189, 199],
       [104,  50, 106, ...,   9, 188, 196],
       ...,
       [106,  54, 101, ...,   4, 187, 201],
       [ 86,  36,  78, ...,  25, 190, 195],
       [ 85,  36,  66, ...,  18, 186, 190]], shape=(846, 18)), array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0]), np.float64(2.8986175115207375), Class
0    74.349882
1    25.650118
Name: proportion, dtype: float64)

In [16]:
print(data_dict["abalone-17_vs_7-8-9-10"])
print(data_dict["ecoli1"])
print(data_dict["glass0"])
print(data_dict["vehicle1"])

(array([[0.35  , 0.265 , 0.09  , ..., 0.0995, 0.0485, 0.07  ],
       [0.33  , 0.255 , 0.08  , ..., 0.0895, 0.0395, 0.055 ],
       [0.355 , 0.28  , 0.085 , ..., 0.095 , 0.0395, 0.115 ],
       ...,
       [0.62  , 0.485 , 0.22  , ..., 0.5095, 0.284 , 0.51  ],
       [0.635 , 0.505 , 0.185 , ..., 0.501 , 0.295 , 0.41  ],
       [0.54  , 0.435 , 0.145 , ..., 0.4285, 0.22  , 0.264 ]],
      shape=(2338, 7)), array([0, 0, 0, ..., 1, 1, 1], shape=(2338,)), np.float64(39.310344827586206), Class
0    97.519247
1     2.480753
Name: proportion, dtype: float64)
(array([[0.49, 0.29, 0.48, ..., 0.56, 0.24, 0.35],
       [0.07, 0.4 , 0.48, ..., 0.54, 0.35, 0.44],
       [0.56, 0.4 , 0.48, ..., 0.49, 0.37, 0.46],
       ...,
       [0.61, 0.6 , 0.48, ..., 0.44, 0.39, 0.38],
       [0.59, 0.61, 0.48, ..., 0.42, 0.42, 0.37],
       [0.74, 0.74, 0.48, ..., 0.31, 0.53, 0.52]], shape=(336, 7)), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0]), np.float64(3.3636363636363638), Class
0    77.083333
1    22.916667
Name: proportion, dtype: float64)
(array([[ 1.51588824, 12.87795   ,  3.43036   , ...,  8.04468   ,
         0.        ,  0.1224    ],
       [ 1.5176423 , 12.9777    ,  3.53812   , ...,  8.52888   ,
         0.        ,  0.        ],
       [ 1.52212996, 14.20795   ,  3.82099   , ...,  9.5726    ,
         0.        ,  0.        ],
       ...,
       [ 1.51837126, 14.321     ,  3.25974   , ...,  5.78508   ,
         1.62855   ,  0.        ],
       [ 1.51657164, 14.7998    ,  0.        , ...,  8.2814    ,
         1.71045   ,  0.        ],
       [ 1.51732338, 14.95275   ,  0.        , ...,  8.61496   ,
         1.5498    ,  0.        ]], shape=(214, 9)), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), np.float64(2.057142857142857), Class
0    67.28972
1    32.71028
Name: proportion, dtype: float64)
(array([[ 95,  48,  83, ...,  16, 187, 197],
       [ 91,  41,  84, ...,  14, 189, 199],
       [104,  50, 106, ...,   9, 188, 196],
       ...,
       [106,  54, 101, ...,   4, 187, 201],
       [ 86,  36,  78, ...,  25, 190, 195],
       [ 85,  36,  66, ...,  18, 186, 190]], shape=(846, 18)), array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0]), np.float64(2.8986175115207375), Class
0    74.349882
1    25.650118
Name: proportion, dtype: float64)

# Models / Pipeline definitions

In [17]:
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import ADASYN
from imblearn.under_sampling import OneSidedSelection, ClusterCentroids

from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

In [18]:
def create_pipeline(architecture, data_level_method=None, params=None):
    steps = []
    
    if data_level_method == "smote":
        steps.append(("smote", SMOTE(random_state=0, sampling_strategy=params[0], k_neighbors=params[1])))
    elif data_level_method == "adasyn":
        steps.append(("adasyn", ADASYN(random_state=0, sampling_strategy=params[0], k_neighbors=params[1])))
    elif data_level_method == "CC":
        steps.append(("CC", ClusterCentroids(random_state=0, sampling_strategy=params[0])))
    
    if architecture == "mlp":
        steps.append((
            "mlp", 
            MLPClassifier(
                (5,10,5), 
                max_iter=2000, 
                solver='adam', 
                learning_rate_init=0.001)
        ))
    elif architecture == "CART":
        steps.append((
            "cart", 
            DecisionTreeClassifier(
                random_state=0)
        ))
        
    
    pipeline = ImbPipeline(steps=steps)
    return pipeline

In [19]:
# pipelines_dict = {}

In [20]:
#pipelines_dict["base_mlp"] = create_pipeline("mlp", data_level_method=None)
#pipelines_dict["smote_mlp"] = create_pipeline("mlp", data_level_method="smote")
#pipelines_dict["adasyn_mlp"] = create_pipeline("mlp", data_level_method="adasyn")

# DONT USE - will

In [21]:
baseline_mlp_template = MLPClassifier(
                (5,10,5), 
                max_iter=2000, 
                solver='adam', 
                learning_rate_init=0.001)

baseline_cart_template = DecisionTreeClassifier(
                random_state=0)

# Parameter searching

In [22]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score
import json

In [23]:
def parameter_grid_resampling(arch, res_mtd ,data, data_key):
    
    print(arch, res_mtd, data_key)
    imb_ratio = data[2]
    inv_imb_ratio = 1.0 / imb_ratio # Used as minima in tuning range
    
    X = data[0]
    y = data[1]
    N_minority = int(np.sum(y))
    print(len(y))
    
    # re-balance ratio (gamma) 10 steps:
    gamma_values = np.linspace(inv_imb_ratio, 1.0, num=10).tolist()
    
    # k values for k-NN based methods:
    k_max = 0
    if 20 <= N_minority:
        k_max = 20
    else:
        k_max = N_minority
        
    k_values = np.linspace(1, k_max,num=3).tolist()
    if res_mtd == "CC":
        k_values = [1]  # ClusterCentroids does not use k_neighbors parameter in the same way, so fix to 1
    
    best_score = -1.0
    best_k = -1
    best_gamma = -1.0
        
    
    for k in k_values:
        print('')
        print('k (Note: ):', k)
        first_g = True
        for g in gamma_values:
            print('g (Note: ):', g)
            params = (g, int(k))
            if first_g:
                first_g = False
                pipeline = create_pipeline(arch) # For when imbalance ratio is 1.0, i.e., no resampling
            else:
                pipeline = create_pipeline(arch, data_level_method=res_mtd, params=params)    
            f1_scores = []
            
            for repetition in range(3):
                
                
                fold_idcs = StratifiedKFold(n_splits=4, shuffle=True).split(X, y)
                for train, test in fold_idcs:
                    pipeline.fit(X[train], y[train])
                    y_pred = pipeline.predict(X[test])
                    
                    score = f1_score(y[test], y_pred, pos_label=1, zero_division=0)
                    f1_scores.append(score)
                    
            param_combo_mean = np.mean(f1_scores)
            if param_combo_mean > best_score:
                best_score = param_combo_mean
                best_k = k
                best_gamma = g
                print('New best found!:', best_score, best_k, best_gamma)
    print('')
    print('Best score:', best_score)
    print('Best k:', best_k)
    print('Best gamma:', best_gamma)
    
    # Write results to file
    with open("test.txt", "a") as myfile:
        myfile.write("\n")
        myfile.write("___")
        myfile.write("\n")
        myfile.write("Architecture: " + arch + "\n")
        myfile.write("Resampling method: " + res_mtd + "\n")
        myfile.write("Dataset: " + data_key + "\n")
        myfile.write("Best F1-score: " + str(best_score) + "\n")
        myfile.write("Best k: " + str(best_k) + "\n")
        myfile.write("Best gamma: " + str(best_gamma) + "\n")
        myfile.write("___")

#### Perform grid search

In [24]:
def search_all_combinations():
    for mtd in ["smote", "CC"]:
        for arch in ["mlp", "CART"]:
            for data_key in data_dict.keys():
                parameter_grid_resampling(arch, mtd, data_dict[data_key], data_key)

In [25]:
search_all_combinations()

# parameter_grid_resampling("CART", "CC", data_dict["abalone-17_vs_7-8-9-10"], "abalone-17_vs_7-8-9-10")
#parameter_grid_resampling("mlp", "CC", data_dict["abalone-17_vs_7-8-9-10"])

mlp smote abalone-17_vs_7-8-9-10
2338

k (Note: ): 1.0
g (Note: ): 0.02543859649122807
New best found!: 0.2528217826205442 1.0 0.02543859649122807
g (Note: ): 0.13372319688109163
New best found!: 0.43027128886869154 1.0 0.13372319688109163
g (Note: ): 0.24200779727095517
g (Note: ): 0.35029239766081877
g (Note: ): 0.4585769980506823
g (Note: ): 0.5668615984405458
g (Note: ): 0.6751461988304094
g (Note: ): 0.7834307992202729
g (Note: ): 0.8917153996101365
g (Note: ): 1.0

k (Note: ): 10.5
g (Note: ): 0.02543859649122807
g (Note: ): 0.13372319688109163
g (Note: ): 0.24200779727095517
g (Note: ): 0.35029239766081877
g (Note: ): 0.4585769980506823
g (Note: ): 0.5668615984405458
g (Note: ): 0.6751461988304094
g (Note: ): 0.7834307992202729
g (Note: ): 0.8917153996101365
g (Note: ): 1.0

k (Note: ): 20.0
g (Note: ): 0.02543859649122807
g (Note: ): 0.13372319688109163

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\joblib\externals\loky\backend\context.py:131: UserWarning: Could not find the number of physical cores for the following reason:
found 0 physical cores < 1
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\joblib\externals\loky\backend\context.py", line 255, in _count_physical_cores
    raise ValueError(f"found {cpu_count_physical} physical cores < 1")

New best found!: 0.43710877757610206 20.0 0.13372319688109163
g (Note: ): 0.24200779727095517
g (Note: ): 0.35029239766081877
g (Note: ): 0.4585769980506823
g (Note: ): 0.5668615984405458
g (Note: ): 0.6751461988304094
g (Note: ): 0.7834307992202729
g (Note: ): 0.8917153996101365
g (Note: ): 1.0

Best score: 0.43710877757610206
Best k: 20.0
Best gamma: 0.13372319688109163
mlp smote ecoli1
336

k (Note: ): 1.0
g (Note: ): 0.2972972972972973
New best found!: 0.7398413929670459 1.0 0.2972972972972973
g (Note: ): 0.37537537537537535
g (Note: ): 0.45345345345345345
New best found!: 0.7598179053991557 1.0 0.45345345345345345
g (Note: ): 0.5315315315315315
g (Note: ): 0.6096096096096095
g (Note: ): 0.6876876876876876
g (Note: ): 0.7657657657657657
g (Note: ): 0.8438438438438438
g (Note: ): 0.9219219219219219
New best found!: 0.7642379948348849 1.0 0.9219219219219219
g (Note: ): 1.0

k (Note: ): 10.5
g (Note: ): 0.2972972972972973
g (Note: ): 0.37537537537537535
g (Note: ): 0.45345345345345345
New best found!: 0.7745725401596889 10.5 0.45345345345345345
g (Note: ): 0.5315315315315315
g (Note: ): 0.6096096096096095
g (Note: ): 0.6876876876876876
g (Note: ): 0.7657657657657657
g (Note: ): 0.8438438438438438
g (Note: ): 0.9219219219219219
g (Note: ): 1.0

k (Note: ): 20.0
g (Note: ): 0.2972972972972973
g (Note: ): 0.37537537537537535
g (Note: ): 0.45345345345345345
g (Note: ): 0.5315315315315315
g (Note: ): 0.6096096096096095
g (Note: ): 0.6876876876876876
g (Note: ): 0.7657657657657657
g (Note: ): 0.8438438438438438
g (Note: ): 0.9219219219219219
g (Note: ): 1.0

Best score: 0.7745725401596889
Best k: 10.5
Best gamma: 0.45345345345345345
mlp smote glass0
214

k (Note: ): 1.0
g (Note: ): 0.48611111111111116
New best found!: 0.12037037037037036 1.0 0.48611111111111116
g (Note: ): 0.54320987654321
New best found!: 0.18676647426647427 1.0 0.54320987654321
g (Note: ): 0.6003086419753086
g (Note: ): 0.6574074074074074
g (Note: ): 0.7145061728395062
g (Note: ): 0.771604938271605
New best found!: 0.23273484532514457 1.0 0.771604938271605
g (Note: ): 0.8287037037037037
New best found!: 0.24816621953945897 1.0 0.8287037037037037
g (Note: ): 0.8858024691358025
g (Note: ): 0.9429012345679013
New best found!: 0.28076985943118665 1.0 0.9429012345679013
g (Note: ): 1.0
New best found!: 0.46002634337415854 1.0 1.0

k (Note: ): 10.5
g (Note: ): 0.48611111111111116
g (Note: ): 0.54320987654321
g (Note: ): 0.6003086419753086
g (Note: ): 0.6574074074074074
g (Note: ): 0.7145061728395062
g (Note: ): 0.771604938271605
g (Note: ): 0.8287037037037037
g (Note: ): 0.8858024691358025
g (Note: ): 0.9429012345679013
g (Note: ): 1.0

k (Note: ): 20.0
g (Note: ): 0.48611111111111116
g (Note: ): 0.54320987654321
g (Note: ): 0.6003086419753086
g (Note: ): 0.6574074074074074
g (Note: ): 0.7145061728395062
g (Note: ): 0.771604938271605
g (Note: ): 0.8287037037037037
g (Note: ): 0.8858024691358025
g (Note: ): 0.9429012345679013
New best found!: 0.5034115491732115 20.0 0.9429012345679013
g (Note: ): 1.0

Best score: 0.5034115491732115
Best k: 20.0
Best gamma: 0.9429012345679013
mlp smote vehicle1
846

k (Note: ): 1.0
g (Note: ): 0.34499205087440377
New best found!: 0.09745161326380623 1.0 0.34499205087440377
g (Note: ): 0.4177707118883589
New best found!: 0.10158069010528026 1.0 0.4177707118883589
g (Note: ): 0.49054937290231404
New best found!: 0.2751233788612596 1.0 0.49054937290231404
g (Note: ): 0.5633280339162692
New best found!: 0.29375587339704 1.0 0.5633280339162692
g (Note: ): 0.6361066949302243
New best found!: 0.3477413868135874 1.0 0.6361066949302243
g (Note: ): 0.7088853559441795
New best found!: 0.37783201149688295 1.0 0.7088853559441795
g (Note: ): 0.7816640169581346
g (Note: ): 0.8544426779720897
New best found!: 0.3870250337312113 1.0 0.8544426779720897
g (Note: ): 0.9272213389860449
New best found!: 0.4221203967390308 1.0 0.9272213389860449
g (Note: ): 1.0
New best found!: 0.49656263096778397 1.0 1.0

k (Note: ): 10.5
g (Note: ): 0.34499205087440377
g (Note: ): 0.4177707118883589
g (Note: ): 0.49054937290231404
g (Note: ): 0.5633280339162692
g (Note: ): 0.6361066949302243
g (Note: ): 0.7088853559441795
g (Note: ): 0.7816640169581346
g (Note: ): 0.8544426779720897
g (Note: ): 0.9272213389860449
g (Note: ): 1.0

k (Note: ): 20.0
g (Note: ): 0.34499205087440377
g (Note: ): 0.4177707118883589
g (Note: ): 0.49054937290231404
g (Note: ): 0.5633280339162692
g (Note: ): 0.6361066949302243
g (Note: ): 0.7088853559441795
g (Note: ): 0.7816640169581346
g (Note: ): 0.8544426779720897
g (Note: ): 0.9272213389860449
New best found!: 0.4992652392249306 20.0 0.9272213389860449
g (Note: ): 1.0

Best score: 0.4992652392249306
Best k: 20.0
Best gamma: 0.9272213389860449
CART smote abalone-17_vs_7-8-9-10
2338

k (Note: ): 1.0
g (Note: ): 0.02543859649122807
New best found!: 0.2188808889473026 1.0 0.02543859649122807
g (Note: ): 0.13372319688109163
New best found!: 0.22761889071214936 1.0 0.13372319688109163
g (Note: ): 0.24200779727095517
New best found!: 0.2383439478498194 1.0 0.24200779727095517
g (Note: ): 0.35029239766081877
New best found!: 0.24434483244710178 1.0 0.35029239766081877
g (Note: ): 0.4585769980506823
New best found!: 0.2553596877195428 1.0 0.4585769980506823
g (Note: ): 0.5668615984405458
New best found!: 0.32711230356216503 1.0 0.5668615984405458
g (Note: ): 0.6751461988304094
g (Note: ): 0.7834307992202729
g (Note: ): 0.8917153996101365
g (Note: ): 1.0

k (Note: ): 10.5
g (Note: ): 0.02543859649122807
g (Note: ): 0.13372319688109163
g (Note: ): 0.24200779727095517
g (Note: ): 0.35029239766081877
g (Note: ): 0.4585769980506823
g (Note: ): 0.5668615984405458
g (Note: ): 0.6751461988304094
g (Note: ): 0.7834307992202729
g (Note: ): 0.8917153996101365
g (Note: ): 1.0

k (Note: ): 20.0
g (Note: ): 0.02543859649122807
g (Note: ): 0.13372319688109163
g (Note: ): 0.24200779727095517
g (Note: ): 0.35029239766081877
g (Note: ): 0.4585769980506823
g (Note: ): 0.5668615984405458
g (Note: ): 0.6751461988304094
g (Note: ): 0.7834307992202729
g (Note: ): 0.8917153996101365
g (Note: ): 1.0

Best score: 0.32711230356216503
Best k: 1.0
Best gamma: 0.5668615984405458
CART smote ecoli1
336

k (Note: ): 1.0
g (Note: ): 0.2972972972972973
New best found!: 0.7328102503725717 1.0 0.2972972972972973
g (Note: ): 0.37537537537537535
New best found!: 0.7389095209129849 1.0 0.37537537537537535
g (Note: ): 0.45345345345345345
g (Note: ): 0.5315315315315315
New best found!: 0.7470100233258128 1.0 0.5315315315315315
g (Note: ): 0.6096096096096095
New best found!: 0.7560307899203919 1.0 0.6096096096096095
g (Note: ): 0.6876876876876876
g (Note: ): 0.7657657657657657
g (Note: ): 0.8438438438438438
g (Note: ): 0.9219219219219219
g (Note: ): 1.0
New best found!: 0.769897554701791 1.0 1.0

k (Note: ): 10.5
g (Note: ): 0.2972972972972973
g (Note: ): 0.37537537537537535
g (Note: ): 0.45345345345345345
g (Note: ): 0.5315315315315315
g (Note: ): 0.6096096096096095
g (Note: ): 0.6876876876876876
g (Note: ): 0.7657657657657657
g (Note: ): 0.8438438438438438
g (Note: ): 0.9219219219219219
g (Note: ): 1.0

k (Note: ): 20.0
g (Note: ): 0.2972972972972973
g (Note: ): 0.37537537537537535
g (Note: ): 0.45345345345345345
New best found!: 0.7747199100014277 20.0 0.45345345345345345
g (Note: ): 0.5315315315315315
g (Note: ): 0.6096096096096095
g (Note: ): 0.6876876876876876
g (Note: ): 0.7657657657657657
g (Note: ): 0.8438438438438438
g (Note: ): 0.9219219219219219
g (Note: ): 1.0

Best score: 0.7747199100014277
Best k: 20.0
Best gamma: 0.45345345345345345
CART smote glass0
214

k (Note: ): 1.0
g (Note: ): 0.48611111111111116
New best found!: 0.6906215247049426 1.0 0.48611111111111116
g (Note: ): 0.54320987654321
g (Note: ): 0.6003086419753086
New best found!: 0.7061288672174535 1.0 0.6003086419753086
g (Note: ): 0.6574074074074074
g (Note: ): 0.7145061728395062
g (Note: ): 0.771604938271605
g (Note: ): 0.8287037037037037
g (Note: ): 0.8858024691358025
g (Note: ): 0.9429012345679013
g (Note: ): 1.0

k (Note: ): 10.5
g (Note: ): 0.48611111111111116
New best found!: 0.7096736172518906 10.5 0.48611111111111116
g (Note: ): 0.54320987654321
g (Note: ): 0.6003086419753086
New best found!: 0.7319314646657394 10.5 0.6003086419753086
g (Note: ): 0.6574074074074074
g (Note: ): 0.7145061728395062
g (Note: ): 0.771604938271605
g (Note: ): 0.8287037037037037
g (Note: ): 0.8858024691358025
g (Note: ): 0.9429012345679013
New best found!: 0.7322689013493123 10.5 0.9429012345679013
g (Note: ): 1.0

k (Note: ): 20.0
g (Note: ): 0.48611111111111116
g (Note: ): 0.54320987654321
g (Note: ): 0.6003086419753086
g (Note: ): 0.6574074074074074
g (Note: ): 0.7145061728395062
g (Note: ): 0.771604938271605
g (Note: ): 0.8287037037037037
g (Note: ): 0.8858024691358025
g (Note: ): 0.9429012345679013
g (Note: ): 1.0

Best score: 0.7322689013493123
Best k: 10.5
Best gamma: 0.9429012345679013
CART smote vehicle1
846

k (Note: ): 1.0
g (Note: ): 0.34499205087440377
New best found!: 0.4911514084787218 1.0 0.34499205087440377
g (Note: ): 0.4177707118883589
New best found!: 0.5129736165356252 1.0 0.4177707118883589
g (Note: ): 0.49054937290231404
g (Note: ): 0.5633280339162692
New best found!: 0.5247109341758313 1.0 0.5633280339162692
g (Note: ): 0.6361066949302243
g (Note: ): 0.7088853559441795
g (Note: ): 0.7816640169581346
g (Note: ): 0.8544426779720897
New best found!: 0.5394741170737625 1.0 0.8544426779720897
g (Note: ): 0.9272213389860449
g (Note: ): 1.0
New best found!: 0.5405850545133571 1.0 1.0

k (Note: ): 10.5
g (Note: ): 0.34499205087440377
g (Note: ): 0.4177707118883589
g (Note: ): 0.49054937290231404
g (Note: ): 0.5633280339162692
g (Note: ): 0.6361066949302243
g (Note: ): 0.7088853559441795
g (Note: ): 0.7816640169581346
g (Note: ): 0.8544426779720897
g (Note: ): 0.9272213389860449
g (Note: ): 1.0

k (Note: ): 20.0
g (Note: ): 0.34499205087440377
g (Note: ): 0.4177707118883589
g (Note: ): 0.49054937290231404
g (Note: ): 0.5633280339162692
g (Note: ): 0.6361066949302243
g (Note: ): 0.7088853559441795
g (Note: ): 0.7816640169581346
g (Note: ): 0.8544426779720897
g (Note: ): 0.9272213389860449
g (Note: ): 1.0
New best found!: 0.5469149285702972 20.0 1.0

Best score: 0.5469149285702972
Best k: 20.0
Best gamma: 1.0
mlp CC abalone-17_vs_7-8-9-10
2338

k (Note: ): 1
g (Note: ): 0.02543859649122807
New best found!: 0.13254114256941016 1 0.02543859649122807
g (Note: ): 0.13372319688109163
New best found!: 0.1451665725578769 1 0.13372319688109163
g (Note: ): 0.24200779727095517
New best found!: 0.18490568490568493 1 0.24200779727095517
g (Note: ): 0.35029239766081877
New best found!: 0.3064349915280127 1 0.35029239766081877
g (Note: ): 0.4585769980506823
g (Note: ): 0.5668615984405458
g (Note: ): 0.6751461988304094
g (Note: ): 0.7834307992202729
g (Note: ): 0.8917153996101365
g (Note: ): 1.0

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Best score: 0.3064349915280127
Best k: 1
Best gamma: 0.35029239766081877
mlp CC ecoli1
336

k (Note: ): 1
g (Note: ): 0.2972972972972973
New best found!: 0.6980081702442368 1 0.2972972972972973
g (Note: ): 0.37537537537537535
g (Note: ): 0.45345345345345345
g (Note: ): 0.5315315315315315
g (Note: ): 0.6096096096096095
g (Note: ): 0.6876876876876876
New best found!: 0.7324786019137646 1 0.6876876876876876
g (Note: ): 0.7657657657657657
g (Note: ): 0.8438438438438438
g (Note: ): 0.9219219219219219
g (Note: ): 1.0

Best score: 0.7324786019137646
Best k: 1
Best gamma: 0.6876876876876876
mlp CC glass0
214

k (Note: ): 1
g (Note: ): 0.48611111111111116
New best found!: 0.14806352184400964 1 0.48611111111111116
g (Note: ): 0.54320987654321
New best found!: 0.2958857093696458 1 0.54320987654321
g (Note: ): 0.6003086419753086
g (Note: ): 0.6574074074074074
g (Note: ): 0.7145061728395062
g (Note: ): 0.771604938271605
g (Note: ): 0.8287037037037037
New best found!: 0.2987515363313006 1 0.8287037037037037
g (Note: ): 0.8858024691358025
New best found!: 0.5392995187713457 1 0.8858024691358025
g (Note: ): 0.9429012345679013
g (Note: ): 1.0

Best score: 0.5392995187713457
Best k: 1
Best gamma: 0.8858024691358025
mlp CC vehicle1
846

k (Note: ): 1
g (Note: ): 0.34499205087440377
New best found!: 0.11325090789376503 1 0.34499205087440377
g (Note: ): 0.4177707118883589
New best found!: 0.1448372847068066 1 0.4177707118883589
g (Note: ): 0.49054937290231404
g (Note: ): 0.5633280339162692
g (Note: ): 0.6361066949302243
g (Note: ): 0.7088853559441795
New best found!: 0.3149494832728085 1 0.7088853559441795
g (Note: ): 0.7816640169581346
g (Note: ): 0.8544426779720897
New best found!: 0.34542196124742414 1 0.8544426779720897
g (Note: ): 0.9272213389860449
New best found!: 0.38442838528467266 1 0.9272213389860449
g (Note: ): 1.0
New best found!: 0.4183403343695955 1 1.0

Best score: 0.4183403343695955
Best k: 1
Best gamma: 1.0
CART CC abalone-17_vs_7-8-9-10
2338

k (Note: ): 1
g (Note: ): 0.02543859649122807
New best found!: 0.22373808576206963 1 0.02543859649122807
g (Note: ): 0.13372319688109163
g (Note: ): 0.24200779727095517
g (Note: ): 0.35029239766081877
g (Note: ): 0.4585769980506823
g (Note: ): 0.5668615984405458
g (Note: ): 0.6751461988304094
g (Note: ): 0.7834307992202729
g (Note: ): 0.8917153996101365
g (Note: ): 1.0

Best score: 0.22373808576206963
Best k: 1
Best gamma: 0.02543859649122807
CART CC ecoli1
336

k (Note: ): 1
g (Note: ): 0.2972972972972973
New best found!: 0.7372341292509361 1 0.2972972972972973
g (Note: ): 0.37537537537537535
g (Note: ): 0.45345345345345345
g (Note: ): 0.5315315315315315
g (Note: ): 0.6096096096096095
g (Note: ): 0.6876876876876876
g (Note: ): 0.7657657657657657
New best found!: 0.7435898111455145 1 0.7657657657657657
g (Note: ): 0.8438438438438438
g (Note: ): 0.9219219219219219
g (Note: ): 1.0

Best score: 0.7435898111455145
Best k: 1
Best gamma: 0.7657657657657657
CART CC glass0
214

k (Note: ): 1
g (Note: ): 0.48611111111111116
New best found!: 0.7243662684931186 1 0.48611111111111116
g (Note: ): 0.54320987654321
g (Note: ): 0.6003086419753086
g (Note: ): 0.6574074074074074
g (Note: ): 0.7145061728395062
g (Note: ): 0.771604938271605
g (Note: ): 0.8287037037037037
g (Note: ): 0.8858024691358025
g (Note: ): 0.9429012345679013
g (Note: ): 1.0

Best score: 0.7243662684931186
Best k: 1
Best gamma: 0.48611111111111116
CART CC vehicle1
846

k (Note: ): 1
g (Note: ): 0.34499205087440377
New best found!: 0.5115186923218645 1 0.34499205087440377
g (Note: ): 0.4177707118883589
g (Note: ): 0.49054937290231404
New best found!: 0.5234639499301273 1 0.49054937290231404
g (Note: ): 0.5633280339162692
g (Note: ): 0.6361066949302243
g (Note: ): 0.7088853559441795
g (Note: ): 0.7816640169581346
g (Note: ): 0.8544426779720897
g (Note: ): 0.9272213389860449
g (Note: ): 1.0

Best score: 0.5234639499301273
Best k: 1
Best gamma: 0.49054937290231404

In [26]:
def parameter_grid_resampling(pipeline_key):
    if pipeline_key == "base_mlp":
        param_grid = {
            # No resampling, so no parameters
        }
    elif pipeline_key in ["smote_mlp", "adasyn_mlp, "]:
        param_grid = {
            # No specific parameters for resampling in this example
        }
    else:
        param_grid = {}
    
    return param_grid

In [27]:
for pipelineKey, pipeline in pipelines_dict.items():
    print(f"Pipeline: {pipelineKey}")
    print(pipelineKey)
    for dataKey, data in data_dict.items():
        
    print()

IndentationError: expected an indented block after 'for' statement on line 4 (3821650964.py, line 6)

# Training and export

In [ ]:
stopHere = True
if stopHere:
    raise SystemExit("Stopped at # Training and export")

SystemExit: Stopped at # Training and export

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\IPython\core\interactiveshell.py:3587: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score
from imblearn.metrics import geometric_mean_score

def shuffle_data_and_train_and_evaluate(X, y, pipeline):
    valid_precisions = []
    valid_recalls = []

    valid_f1s = []
    valid_gmeans = []
    valid_aucs = []

    runs_target = 100
    runs_cur = 0
    seed = 0

    while runs_cur < runs_target:
        # Random Split
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, 
            test_size=0.3, 
            stratify=None, 
            random_state=seed
        )
        
        n_minority = sum(y_test == 1)
        
        if n_minority >= 10:
            # Scale
            scaler = StandardScaler()
            X_train = scaler.fit_transform(X_train)
            X_test = scaler.transform(X_test)
            
            # Train
            pipeline.fit(X_train, y_train)
            y_pred = pipeline.predict(X_test)
            y_score = pipeline.predict_proba(X_test)[:, 1] # For AUC calculation
            
            valid_precisions.append(precision_score(y_test, y_pred, pos_label=1, zero_division=0))
            valid_recalls.append(recall_score(y_test, y_pred, pos_label=1, zero_division=0))
            valid_f1s.append(f1_score(y_test, y_pred, pos_label=1, zero_division=0))
            valid_gmeans.append(geometric_mean_score(y_test, y_pred, pos_label=1))
            valid_aucs.append(roc_auc_score(y_test, y_score))
            
            runs_cur += 1
            
            if runs_cur % 10 == 0:
                print(f"Run {runs_cur}/{runs_target} completed...")

        seed += 1


    print(f"Seeds checked: {seed}")
    print(f"Average Precision: {np.mean(valid_precisions):.4f}")
    print(f"Average Recall:    {np.mean(valid_recalls):.4f}")
    print("")
    print(f"Average F1:        {np.mean(valid_f1s):.4f}")
    print(f"Standard deviation F1: {np.std(valid_f1s):.4f}")
    print(f"Average G-Mean:    {np.mean(valid_gmeans):.4f}")
    print(f"standard deviation G-Mean: {np.std(valid_gmeans):.4f}")
    print(f"Average AUC:      {np.mean(valid_aucs):.4f}")
    print(f"standard deviation AUC: {np.std(valid_aucs):.4f}")
    
    output_dict = {
        "average_precision": np.mean(valid_precisions),
        "average_recall": np.mean(valid_recalls),
        "average_f1": np.mean(valid_f1s),
        "std_f1": np.std(valid_f1s),
        "average_gmean": np.mean(valid_gmeans),
        "std_gmean": np.std(valid_gmeans),
        "average_auc": np.mean(valid_aucs),
        "std_auc": np.std(valid_aucs)
    }
    
    return output_dict

In [ ]:
import json
from datetime import datetime

#results_1 = shuffle_data_and_train_and_evaluate(X, y, pipelines_dict["base_mlp"])
#results_2 = shuffle_data_and_train_and_evaluate(X, y, pipelines_dict["smote_mlp"])
#results_3 = shuffle_data_and_train_and_evaluate(X, y, pipelines_dict["adasyn_mlp"])

# iterate through pipelines dict and train the model for each, add results to new dict
results_dict = {}
for name, pipeline in pipelines_dict.items():
    print(f"Training and evaluating pipeline: {name}")
    for dataset_name, (X, y, imb_ratio, imb_count) in data_dict.items():
        print(f"Dataset: {dataset_name} (Imbalance Ratio: {imb_ratio:.2f})")
        results = shuffle_data_and_train_and_evaluate(X, y, pipeline)
        results_dict[f"{name}_{dataset_name}"] = results
        print("\n" + "="*10 + "\n")
    print("\n" + "="*50 + "\n")
    

cur_date = datetime.now().strftime("%Y%m%d_%H%M%S")
with open("binary_classification_results" + cur_date + ".json", "w") as f:
    json.dump(results_dict, f, indent=4)

Training and evaluating pipeline: base_mlp
Dataset: abalone-17_vs_7-8-9-10 (Imbalance Ratio: 39.31)
Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...
Run 40/100 completed...
Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.4436
Average Recall:    0.1364

Average F1:        0.1971
Standard deviation F1: 0.1470
Average G-Mean:    0.3048
standard deviation G-Mean: 0.2070
Average AUC:      0.9182
standard deviation AUC: 0.0690

==========

Dataset: ecoli1 (Imbalance Ratio: 3.36)
Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...
Run 40/100 completed...
Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.7847
Average Recall:    0.7674

Average F1:        0.7681
Standard deviation F1: 0.0599
Average G-Mean:    0.8454
standard deviation G-Mean: 0.0524
Average AUC:      0.9461
standard deviation AUC: 0.0287

==========

Dataset: glass0 (Imbalance Ratio: 2.06)
Run 10/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 20/100 completed...
Run 30/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 40/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 50/100 completed...
Run 60/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 70/100 completed...
Run 80/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.6804
Average Recall:    0.6905

Average F1:        0.6781
Standard deviation F1: 0.0810
Average G-Mean:    0.7595
standard deviation G-Mean: 0.0635
Average AUC:      0.8494
standard deviation AUC: 0.0408

==========

Dataset: vehicle1 (Imbalance Ratio: 2.90)
Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 40/100 completed...
Run 50/100 completed...
Run 60/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.6653
Average Recall:    0.6767

Average F1:        0.6668
Standard deviation F1: 0.0513
Average G-Mean:    0.7703
standard deviation G-Mean: 0.0433
Average AUC:      0.8965
standard deviation AUC: 0.0292

==========


==================================================

Training and evaluating pipeline: smote_mlp
Dataset: abalone-17_vs_7-8-9-10 (Imbalance Ratio: 39.31)
Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...
Run 40/100 completed...
Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.2279
Average Recall:    0.6932

Average F1:        0.3386
Standard deviation F1: 0.0534
Average G-Mean:    0.8030
standard deviation G-Mean: 0.0737
Average AUC:      0.9152
standard deviation AUC: 0.0408

==========

Dataset: ecoli1 (Imbalance Ratio: 3.36)
Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...
Run 40/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.6995
Average Recall:    0.8525

Average F1:        0.7633
Standard deviation F1: 0.0607
Average G-Mean:    0.8699
standard deviation G-Mean: 0.0401
Average AUC:      0.9441
standard deviation AUC: 0.0265

==========

Dataset: glass0 (Imbalance Ratio: 2.06)
Run 10/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 20/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 30/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 40/100 completed...
Run 50/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.6413
Average Recall:    0.7713

Average F1:        0.6945
Standard deviation F1: 0.0790
Average G-Mean:    0.7745
standard deviation G-Mean: 0.0589
Average AUC:      0.8457
standard deviation AUC: 0.0489

==========

Dataset: vehicle1 (Imbalance Ratio: 2.90)

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\joblib\externals\loky\backend\context.py:131: UserWarning: Could not find the number of physical cores for the following reason:
found 0 physical cores < 1
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\joblib\externals\loky\backend\context.py", line 255, in _count_physical_cores
    raise ValueError(f"found {cpu_count_physical} physical cores < 1")

Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...
Run 40/100 completed...
Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.6268
Average Recall:    0.7642

Average F1:        0.6863
Standard deviation F1: 0.0449
Average G-Mean:    0.8012
standard deviation G-Mean: 0.0321
Average AUC:      0.8950
standard deviation AUC: 0.0243

==========


==================================================

Training and evaluating pipeline: adasyn_mlp
Dataset: abalone-17_vs_7-8-9-10 (Imbalance Ratio: 39.31)
Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...
Run 40/100 completed...
Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.2223
Average Recall:    0.6980

Average F1:        0.3327
Standard deviation F1: 0.0528
Average G-Mean:    0.8042
standard deviation G-Mean: 0.0749
Average AUC:      0.9171
standard deviation AUC: 0.0367

==========

Dataset: ecoli1 (Imbalance Ratio: 3.36)
Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 40/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.6614
Average Recall:    0.8613

Average F1:        0.7432
Standard deviation F1: 0.0531
Average G-Mean:    0.8642
standard deviation G-Mean: 0.0345
Average AUC:      0.9403
standard deviation AUC: 0.0228

==========

Dataset: glass0 (Imbalance Ratio: 2.06)
Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...
Run 40/100 completed...
Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.6053
Average Recall:    0.7917

Average F1:        0.6785
Standard deviation F1: 0.0871
Average G-Mean:    0.7501
standard deviation G-Mean: 0.1231
Average AUC:      0.8294
standard deviation AUC: 0.0588

==========

Dataset: vehicle1 (Imbalance Ratio: 2.90)
Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...
Run 40/100 completed...
Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.6203
Average Recall:    0.7682

Average F1:        0.6834
Standard deviation F1: 0.0446
Average G-Mean:    0.8005
standard deviation G-Mean: 0.0344
Average AUC:      0.8902
standard deviation AUC: 0.0230

==========


==================================================