## Utils

# Data

In [5]:


import numpy as np
import os.path
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [6]:
data_dict = {}

## Abalone-17_vs_7-8-9-10 dataset

### Prepare data

In [7]:
file_name = "./datasets/abalone-17_vs_7-8-9-10/abalone-17_vs_7-8-9-10.dat"
#if os.path.exists(file_name):
#    print("exists")

df = pd.read_csv(
    file_name,
    comment='@',
    header=None,
    sep=','
)

columns = [
    "Sex", "Length", "Diameter", "Height",
    "Whole_weight", "Shucked_weight",
    "Viscera_weight", "Shell_weight",
    "Class"
]

df.columns = columns

df = pd.get_dummies(df, columns=["Sex"], dtype=int)

# print(df["Class"].unique())
df["Class"] = df["Class"].map({" negative": 0, " positive": 1})

X = df.drop("Class", axis=1).values
y = df["Class"].values

df

#folds = load_data(file_name, type_data="imbalanced", raw=True)

,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Class,Sex_F,Sex_I,Sex_M
0,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,0,0,0,1
1,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,0,0,1,0
2,0.355,0.280,0.085,0.2905,0.0950,0.0395,0.115,0,0,1,0
3,0.365,0.295,0.080,0.2555,0.0970,0.0430,0.100,0,0,0,1
4,0.390,0.295,0.095,0.2030,0.0875,0.0450,0.075,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
2333,0.570,0.440,0.140,0.9535,0.3785,0.2010,0.305,1,1,0,0
2334,0.585,0.455,0.125,1.0270,0.3910,0.2120,0.250,1,0,0,1
2335,0.620,0.485,0.220,1.5110,0.5095,0.2840,0.510,1,1,0,0
2336,0.635,0.505,0.185,1.3035,0.5010,0.2950,0.410,1,1,0,0
2337,0.540,0.435,0.145,0.9700,0.4285,0.2200,0.264,1,0,1,0

### Data cleaning

In [8]:
X = df.drop(columns=["Class", "Sex_F", "Sex_I", "Sex_M"], errors='ignore').values
y = df["Class"].values

count_class = df["Class"].value_counts()

imb_count = df["Class"].value_counts(normalize=True) * 100
imb_count

imb_ratio = count_class.max() / count_class.min()
imb_ratio

data_dict['abalone-17_vs_7-8-9-10'] = (X, y, imb_ratio, imb_count)
print(data_dict['abalone-17_vs_7-8-9-10'])

(array([[0.35  , 0.265 , 0.09  , ..., 0.0995, 0.0485, 0.07  ],
       [0.33  , 0.255 , 0.08  , ..., 0.0895, 0.0395, 0.055 ],
       [0.355 , 0.28  , 0.085 , ..., 0.095 , 0.0395, 0.115 ],
       ...,
       [0.62  , 0.485 , 0.22  , ..., 0.5095, 0.284 , 0.51  ],
       [0.635 , 0.505 , 0.185 , ..., 0.501 , 0.295 , 0.41  ],
       [0.54  , 0.435 , 0.145 , ..., 0.4285, 0.22  , 0.264 ]],
      shape=(2338, 7)), array([0, 0, 0, ..., 1, 1, 1], shape=(2338,)), np.float64(39.310344827586206), Class
0    97.519247
1     2.480753
Name: proportion, dtype: float64)

In [9]:
print(1/data_dict["abalone-17_vs_7-8-9-10"][2])

0.02543859649122807

## ecoli1 dataset

In [10]:
file_name = "./datasets/ecoli1/ecoli1.dat"
#if os.path.exists(file_name):
#    print("exists")

df = pd.read_csv(
    file_name,
    comment='@',
    header=None,
    sep=','
)

columns = [
    "Mcg", "Gvh", "Lip", "Chg",
    "Aac", "Alm1", "Alm2", "Class"
]

df.columns = columns

# set Class values to 0 and 1 but match even if trailing spaces after "positive" and "negative"

df["Class"] = df["Class"].map({" negative": 0, " positive": 1, " negative    ": 0})

X = df.drop("Class", axis=1).values
y = df["Class"].values

df

#folds = load_data(file_name, type_data="imbalanced", raw=True)

      Mcg   Gvh   Lip  Chg   Aac  Alm1  Alm2  Class
0    0.49  0.29  0.48  0.5  0.56  0.24  0.35      0
1    0.07  0.40  0.48  0.5  0.54  0.35  0.44      0
2    0.56  0.40  0.48  0.5  0.49  0.37  0.46      0
3    0.59  0.49  0.48  0.5  0.52  0.45  0.36      0
4    0.23  0.32  0.48  0.5  0.55  0.25  0.35      0
..    ...   ...   ...  ...   ...   ...   ...    ...
331  0.74  0.56  0.48  0.5  0.47  0.68  0.30      0
332  0.71  0.57  0.48  0.5  0.48  0.35  0.32      0
333  0.61  0.60  0.48  0.5  0.44  0.39  0.38      0
334  0.59  0.61  0.48  0.5  0.42  0.42  0.37      0
335  0.74  0.74  0.48  0.5  0.31  0.53  0.52      0

[336 rows x 8 columns]

In [11]:
X = df.drop(columns=["Class"], errors='ignore').values # Note that there are a few NaNs after defining df so errors ignore is needed, gives a slightly different imbalance ratio
y = df["Class"].values

count_class = df["Class"].value_counts()

imb_count = df["Class"].value_counts(normalize=True) * 100
imb_count

imb_ratio = count_class.max() / count_class.min()
imb_ratio

data_dict['ecoli1'] = (X, y, imb_ratio, imb_count)
print(data_dict['ecoli1'])

(array([[0.49, 0.29, 0.48, ..., 0.56, 0.24, 0.35],
       [0.07, 0.4 , 0.48, ..., 0.54, 0.35, 0.44],
       [0.56, 0.4 , 0.48, ..., 0.49, 0.37, 0.46],
       ...,
       [0.61, 0.6 , 0.48, ..., 0.44, 0.39, 0.38],
       [0.59, 0.61, 0.48, ..., 0.42, 0.42, 0.37],
       [0.74, 0.74, 0.48, ..., 0.31, 0.53, 0.52]], shape=(336, 7)), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0]), np.float64(3.3636363636363638), Class
0    77.083333
1    22.916667
Name: proportion, dtype: float64)

## glass0 Dataset

In [13]:
file_name = "./datasets/glass0/glass0.dat"
#if os.path.exists(file_name):
#    print("exists")

df = pd.read_csv(
    file_name,
    comment='@',
    header=None,
    sep=','
)

columns = [
    "RI", "Na", "Mg", "Al", "Si", "K", "Ca", "Ba", "Fe", "Class"
]

df.columns = columns

# print(df["Class"].unique())
df["Class"] = df["Class"].map({" negative": 0, " positive": 1})

X = df.drop("Class", axis=1).values
y = df["Class"].values

df

#folds = load_data(file_name, type_data="imbalanced", raw=True)

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Class
0,1.515888,12.87795,3.43036,1.40066,73.2820,0.68931,8.04468,0.00000,0.1224,1
1,1.517642,12.97770,3.53812,1.21127,73.0020,0.65205,8.52888,0.00000,0.0000,1
2,1.522130,14.20795,3.82099,0.46976,71.7700,0.11178,9.57260,0.00000,0.0000,1
3,1.522221,13.21045,3.77160,0.79076,71.9884,0.13041,10.24520,0.00000,0.0000,1
4,1.517551,13.39000,3.65935,1.18880,72.7892,0.57132,8.27064,0.00000,0.0561,1
...,...,...,...,...,...,...,...,...,...,...
209,1.517278,14.70005,0.00000,2.34119,73.2820,0.00000,8.94852,0.66150,0.0000,0
210,1.516230,14.14145,0.00000,2.88047,72.6100,0.08073,9.18524,1.06155,0.0000,0
211,1.518371,14.32100,3.25974,2.21921,71.2492,1.45935,5.78508,1.62855,0.0000,0
212,1.516572,14.79980,0.00000,1.99130,73.1084,0.00000,8.28140,1.71045,0.0000,0
213,1.517323,14.95275,0.00000,1.79870,72.9908,0.00000,8.61496,1.54980,0.0000,0

In [14]:
X = df.drop(columns=["Class"], errors='ignore').values # Note that there are a few NaNs after defining df so errors ignore is needed, gives a slightly different imbalance ratio
y = df["Class"].values

count_class = df["Class"].value_counts()

imb_count = df["Class"].value_counts(normalize=True) * 100
imb_count

imb_ratio = count_class.max() / count_class.min()
imb_ratio

data_dict['glass0'] = (X, y, imb_ratio, imb_count)
print(data_dict['glass0'])

(array([[ 1.51588824, 12.87795   ,  3.43036   , ...,  8.04468   ,
         0.        ,  0.1224    ],
       [ 1.5176423 , 12.9777    ,  3.53812   , ...,  8.52888   ,
         0.        ,  0.        ],
       [ 1.52212996, 14.20795   ,  3.82099   , ...,  9.5726    ,
         0.        ,  0.        ],
       ...,
       [ 1.51837126, 14.321     ,  3.25974   , ...,  5.78508   ,
         1.62855   ,  0.        ],
       [ 1.51657164, 14.7998    ,  0.        , ...,  8.2814    ,
         1.71045   ,  0.        ],
       [ 1.51732338, 14.95275   ,  0.        , ...,  8.61496   ,
         1.5498    ,  0.        ]], shape=(214, 9)), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), np.float64(2.057142857142857), Class
0    67.28972
1    32.71028
Name: proportion, dtype: float64)

## vehicle1 Dataset - *This one only has integer valued data*

In [15]:
file_name = "./datasets/vehicle1/vehicle1.dat"
#if os.path.exists(file_name):
#    print("exists")

df = pd.read_csv(
    file_name,
    comment='@',
    header=None,
    sep=','
)

columns = [
    "Compactness", 
    "Circularity", 
    "Distance_circularity", 
    "Radius_ratio", 
    "Praxis_aspect_ratio", 
    "Max_length_aspect_ratio", 
    "Scatter_ratio", 
    "Elongatedness", 
    "Praxis_rectangular", 
    "Length_rectangular", 
    "Major_variance", 
    "Minor_variance", 
    "Gyration_radius", 
    "Major_skewness", 
    "Minor_skewness", 
    "Minor_kurtosis", 
    "Major_kurtosis", 
    "Hollows_ratio", 
    "Class"
]

df.columns = columns

# print(df["Class"].unique())
df["Class"] = df["Class"].map({" negative": 0, " positive": 1, " positive ": 1, " negative ": 0})

X = df.drop("Class", axis=1).values
y = df["Class"].values

df

#folds = load_data(file_name, type_data="imbalanced", raw=True)

,Compactness,Circularity,Distance_circularity,Radius_ratio,Praxis_aspect_ratio,Max_length_aspect_ratio,Scatter_ratio,Elongatedness,Praxis_rectangular,Length_rectangular,Major_variance,Minor_variance,Gyration_radius,Major_skewness,Minor_skewness,Minor_kurtosis,Major_kurtosis,Hollows_ratio,Class
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,0
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,0
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,1
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,0
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,93,39,87,183,64,8,169,40,20,134,200,422,149,72,7,25,188,195,1
842,89,46,84,163,66,11,159,43,20,159,173,368,176,72,1,20,186,197,0
843,106,54,101,222,67,12,222,30,25,173,228,721,200,70,3,4,187,201,1
844,86,36,78,146,58,7,135,50,18,124,155,270,148,66,0,25,190,195,1
845,85,36,66,123,55,5,120,56,17,128,140,212,131,73,1,18,186,190,0

In [16]:
X = df.drop(columns=["Class"], errors='ignore').values 
y = df["Class"].values

count_class = df["Class"].value_counts()

imb_count = df["Class"].value_counts(normalize=True) * 100
imb_count

imb_ratio = count_class.max() / count_class.min()
print(imb_ratio)

data_dict['vehicle1'] = (X, y, imb_ratio, imb_count)
print(data_dict['vehicle1'])

2.8986175115207375
(array([[ 95,  48,  83, ...,  16, 187, 197],
       [ 91,  41,  84, ...,  14, 189, 199],
       [104,  50, 106, ...,   9, 188, 196],
       ...,
       [106,  54, 101, ...,   4, 187, 201],
       [ 86,  36,  78, ...,  25, 190, 195],
       [ 85,  36,  66, ...,  18, 186, 190]], shape=(846, 18)), array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0]), np.float64(2.8986175115207375), Class
0    74.349882
1    25.650118
Name: proportion, dtype: float64)

In [17]:
print(data_dict["abalone-17_vs_7-8-9-10"])
print(data_dict["ecoli1"])
print(data_dict["glass0"])
print(data_dict["vehicle1"])

(array([[0.35  , 0.265 , 0.09  , ..., 0.0995, 0.0485, 0.07  ],
       [0.33  , 0.255 , 0.08  , ..., 0.0895, 0.0395, 0.055 ],
       [0.355 , 0.28  , 0.085 , ..., 0.095 , 0.0395, 0.115 ],
       ...,
       [0.62  , 0.485 , 0.22  , ..., 0.5095, 0.284 , 0.51  ],
       [0.635 , 0.505 , 0.185 , ..., 0.501 , 0.295 , 0.41  ],
       [0.54  , 0.435 , 0.145 , ..., 0.4285, 0.22  , 0.264 ]],
      shape=(2338, 7)), array([0, 0, 0, ..., 1, 1, 1], shape=(2338,)), np.float64(39.310344827586206), Class
0    97.519247
1     2.480753
Name: proportion, dtype: float64)
(array([[0.49, 0.29, 0.48, ..., 0.56, 0.24, 0.35],
       [0.07, 0.4 , 0.48, ..., 0.54, 0.35, 0.44],
       [0.56, 0.4 , 0.48, ..., 0.49, 0.37, 0.46],
       ...,
       [0.61, 0.6 , 0.48, ..., 0.44, 0.39, 0.38],
       [0.59, 0.61, 0.48, ..., 0.42, 0.42, 0.37],
       [0.74, 0.74, 0.48, ..., 0.31, 0.53, 0.52]], shape=(336, 7)), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0]), np.float64(3.3636363636363638), Class
0    77.083333
1    22.916667
Name: proportion, dtype: float64)
(array([[ 1.51588824, 12.87795   ,  3.43036   , ...,  8.04468   ,
         0.        ,  0.1224    ],
       [ 1.5176423 , 12.9777    ,  3.53812   , ...,  8.52888   ,
         0.        ,  0.        ],
       [ 1.52212996, 14.20795   ,  3.82099   , ...,  9.5726    ,
         0.        ,  0.        ],
       ...,
       [ 1.51837126, 14.321     ,  3.25974   , ...,  5.78508   ,
         1.62855   ,  0.        ],
       [ 1.51657164, 14.7998    ,  0.        , ...,  8.2814    ,
         1.71045   ,  0.        ],
       [ 1.51732338, 14.95275   ,  0.        , ...,  8.61496   ,
         1.5498    ,  0.        ]], shape=(214, 9)), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), np.float64(2.057142857142857), Class
0    67.28972
1    32.71028
Name: proportion, dtype: float64)
(array([[ 95,  48,  83, ...,  16, 187, 197],
       [ 91,  41,  84, ...,  14, 189, 199],
       [104,  50, 106, ...,   9, 188, 196],
       ...,
       [106,  54, 101, ...,   4, 187, 201],
       [ 86,  36,  78, ...,  25, 190, 195],
       [ 85,  36,  66, ...,  18, 186, 190]], shape=(846, 18)), array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0]), np.float64(2.8986175115207375), Class
0    74.349882
1    25.650118
Name: proportion, dtype: float64)

# Models / Pipeline definitions

In [2]:
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import ADASYN
from imblearn.under_sampling import OneSidedSelection, ClusterCentroids

from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

### LNR implementation

##### Our implementation

In [3]:
def get_mlp_lnr(max_iter): # LNR-MLP has different max_iter than classifier MLP
    lnr_clf = MLPClassifier(
                (5,10,5), 
                max_iter=max_iter, 
                solver='adam', 
                learning_rate_init=0.001)
    return lnr_clf

In [ ]:


def apply_lnr(clf, X, y, t_flip):
    
    ind_MA = np.where(y == 0)
    
    N = ind_MA[0].shape[0]

    eta_hat = np.zeros(N)
    Z = np.zeros(N)
    rho = np.zeros(N)
    
    probs = clf.predict_proba(X) # Does softmax internally
    
    probs_MA = probs[ind_MA, 1].flatten()  # False positive rates

    mu = np.mean(probs_MA, axis=0)
    std = np.std(probs_MA, axis=0)
    
    Z = (probs_MA - mu) / (std + 1e-8)
    
    stack = np.stack((np.tanh(Z - t_flip), np.zeros(Z.shape)), axis=1)
    
    rho = np.max(stack,axis=1)
    
    U = np.random.uniform(0, 1, N)
    ind_flip = np.where(U < rho)
    y_new = y.copy()
    y_new[ind_MA[0][ind_flip]] = 1  # Flip labels to minority class 
    
    return y_new

    
# Some debugging
data_key = 'abalone-17_vs_7-8-9-10'
X, y, imb_ratio, imb_count = data_dict[data_key]
test_mlp = get_mlp_lnr(50)
test_mlp.fit(X, y)
apply_lnr(test_mlp, X, y, t_flip=1.0)

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(

array([0, 0, 0, ..., 1, 1, 1], shape=(2338,))

##### LNR cifar repo version

### The rest

In [19]:
def create_pipeline(architecture, data_level_method=None, params=None):
    steps = []
    
    if data_level_method == "smote":
        steps.append(("smote", SMOTE(random_state=0, sampling_strategy=params[0], k_neighbors=params[1])))
    elif data_level_method == "adasyn":
        steps.append(("adasyn", ADASYN(random_state=0, sampling_strategy=params[0], k_neighbors=params[1])))
    elif data_level_method == "CC":
        steps.append(("CC", ClusterCentroids(random_state=0, sampling_strategy=params[0])))
    
    if architecture == "mlp":
        steps.append((
            "mlp", 
            MLPClassifier(
                (5,10,5), 
                max_iter=2000, 
                solver='adam', 
                learning_rate_init=0.001)
        ))
    elif architecture == "CART":
        steps.append((
            "cart", 
            DecisionTreeClassifier(
                random_state=0)
        ))
        
    
    pipeline = ImbPipeline(steps=steps)
    return pipeline

In [20]:
baseline_mlp_template = MLPClassifier(
                (5,10,5), 
                max_iter=2000, 
                solver='adam', 
                learning_rate_init=0.001)

baseline_cart_template = DecisionTreeClassifier(
                random_state=0)

# Parameter searching

In [21]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score
import json

## LNR param search

In [22]:
import copy
import numpy as np
def parameter_grid_lnr(data, data_key):
    
    t_flip_schedule = np.linspace(0.0, 4.0, num=10).tolist()
    n_epochs_schedule = np.linspace(100, 4000, num=3, dtype='int16').tolist()
    

    
    X = data[0]
    y = data[1]
    
    best_score_mlp = -1.0
    best_t_flip_mlp = -1.0
    best_n_epochs_mlp = -1
    
    best_score_cart = -1.0
    best_t_flip_cart = -1.0
    best_n_epochs_cart = -1
    
    
    
    
        
    
    for t_flip in t_flip_schedule:
        print('')
        print('t_flip (Note: ):', t_flip)
        for n_epochs in n_epochs_schedule:
            print('n_epochs (Note: ):', n_epochs)
            mlp_nlp = get_mlp_lnr(max_iter=n_epochs)
            f1_scores_mlp = []
            f1_scores_cart = []
            
            for repetition in range(3):
                
                cart_clf = create_pipeline("CART")
                mlp_clf = create_pipeline("mlp")
                
                
                fold_idcs = StratifiedKFold(n_splits=4, shuffle=True).split(X, y)
                for train, test in fold_idcs:
                    
                    # Fit mlp for LNR
                    mlp_nlp.fit(X[train], y[train])
                    y_train_new = apply_lnr(mlp_nlp, X[train], y[train], t_flip)
                    
                    # Fit mlp classifier on new labels
                    mlp_clf.fit(X[train], y_train_new)
                    y_pred_mlp = mlp_clf.predict(X[test])
                    score_mlp = f1_score(y[test], y_pred_mlp, pos_label=1, zero_division=0)
                    f1_scores_mlp.append(score_mlp)
                    
                    # Fit cart on new labels
                    cart_clf.fit(X[train], y_train_new)
                    y_pred_cart = cart_clf.predict(X[test])
                    score_cart = f1_score(y[test], y_pred_cart, pos_label=1, zero_division=0)
                    f1_scores_cart.append(score_cart)
                    
            param_combo_mean_mlp = np.mean(f1_scores_mlp)
            param_combo_mean_cart = np.mean(f1_scores_cart)
            
            if param_combo_mean_mlp > best_score_mlp:
                best_score_mlp = param_combo_mean_mlp
                best_t_flip_mlp = t_flip
                best_n_epochs_mlp = n_epochs
                print('New best found for mlp!:', best_score_mlp, best_t_flip_mlp, best_n_epochs_mlp)
            if param_combo_mean_cart > best_score_cart:
                best_score_cart = param_combo_mean_cart
                best_t_flip_cart = t_flip
                best_n_epochs_cart = n_epochs
                print('New best found for cart!:', best_score_cart, best_t_flip_cart, best_n_epochs_cart)
                
    print('')
    print('Best score mlp:', best_score_mlp)
    print('Best t_flip mlp:', best_t_flip_mlp)
    print('Best n_epochs mlp:', best_n_epochs_mlp)
    print('Best score cart:', best_score_cart)
    print('Best t_flip cart:', best_t_flip_cart)
    print('Best n_epochs cart:', best_n_epochs_cart)
    
    # Write results to file
    with open("LNR_SEARCH_" + data_key + ".txt", "a") as myfile:
        myfile.write("\n")
        myfile.write("___")
        myfile.write("\n")
        myfile.write("Architecture: " + "mlp" + "\n")
        myfile.write("Best F1-score: " + str(best_score_mlp) + "\n")
        myfile.write("Best t_flip: " + str(best_t_flip_mlp) + "\n")
        myfile.write("Best n_epochs: " + str(best_n_epochs_mlp) + "\n")
        myfile.write("___")
        myfile.write("\n")
        myfile.write("___")
        myfile.write("\n")
        
        myfile.write("Architecture: " + "cart" + "\n")
        myfile.write("Best F1-score: " + str(best_score_cart) + "\n")
        myfile.write("Best t_flip: " + str(best_t_flip_cart) + "\n")
        myfile.write("Best n_epochs: " + str(best_n_epochs_cart) + "\n")
        myfile.write("___")
    
    output_dict = {}
    output_dict['t_flip_cart'] = best_t_flip_cart
    output_dict['n_epochs_cart'] = best_n_epochs_cart
    output_dict['t_flip_mlp'] = best_t_flip_mlp
    output_dict['n_epochs_mlp'] = best_n_epochs_mlp
        
    return output_dict

In [ ]:
#parameter_grid_lnr(data_dict["abalone-17_vs_7-8-9-10"], "abalone-17_vs_7-8-9-10")
parameter_grid_lnr(data_dict["ecoli1"], "ecoli1")
parameter_grid_lnr(data_dict["glass0"], "glass0")
parameter_grid_lnr(data_dict["vehicle1"], "vehicle1")

## resampling methods param search

In [ ]:
import copy
def parameter_grid_resampling(arch, res_mtd ,data, data_key):
    
    print(arch, res_mtd, data_key)
    imb_ratio = data[2]
    inv_imb_ratio = 1.0 / imb_ratio # Used as minima in tuning range
    
    X = data[0]
    y = data[1]
    N_minority = int(np.sum(y))
    print(len(y))
    
    # re-balance ratio (gamma) 10 steps:
    gamma_values = np.linspace(inv_imb_ratio, 1.0, num=10).tolist()
    
    # k values for k-NN based methods:
    k_max = 0
    if 20 <= N_minority:
        k_max = 20
    else:
        k_max = N_minority
        
    k_values = np.linspace(1, k_max,num=3).tolist()
    if res_mtd == "CC":
        k_values = [1]  # ClusterCentroids does not use k_neighbors parameter in the same way, so fix to 1
    
    best_score = -1.0
    best_k = -1
    best_gamma = -1.0
    
    best_pipeline = None
        
    
    for k in k_values:
        print('')
        print('k (Note: ):', k)
        first_g = True
        for g in gamma_values:
            print('g (Note: ):', g)
            params = (g, int(k))
            if first_g:
                first_g = False
                pipeline = create_pipeline(arch) # For when imbalance ratio is 1.0, i.e., no resampling
            else:
                pipeline = create_pipeline(arch, data_level_method=res_mtd, params=params)    
            f1_scores = []
            
            for repetition in range(3):
                
                
                fold_idcs = StratifiedKFold(n_splits=4, shuffle=True).split(X, y)
                for train, test in fold_idcs:
                    pipeline.fit(X[train], y[train])
                    y_pred = pipeline.predict(X[test])
                    
                    score = f1_score(y[test], y_pred, pos_label=1, zero_division=0)
                    f1_scores.append(score)
                    
            param_combo_mean = np.mean(f1_scores)
            if param_combo_mean > best_score:
                best_score = param_combo_mean
                best_k = k
                best_gamma = g
                print('New best found!:', best_score, best_k, best_gamma)
                best_pipeline = copy.deepcopy(pipeline)
                
    print('')
    print('Best score:', best_score)
    print('Best k:', best_k)
    print('Best gamma:', best_gamma)
    
    # Write results to file
    with open("test.txt", "a") as myfile:
        myfile.write("\n")
        myfile.write("___")
        myfile.write("\n")
        myfile.write("Architecture: " + arch + "\n")
        myfile.write("Resampling method: " + res_mtd + "\n")
        myfile.write("Dataset: " + data_key + "\n")
        myfile.write("Best F1-score: " + str(best_score) + "\n")
        myfile.write("Best k: " + str(best_k) + "\n")
        myfile.write("Best gamma: " + str(best_gamma) + "\n")
        myfile.write("___")
        
    return best_pipeline, (best_gamma, int(best_k))

#### Perform grid search

In [24]:
def search_all_combinations():
    for mtd in ["smote", "CC"]:
        for arch in ["mlp", "CART"]:
            for data_key in data_dict.keys():
                parameter_grid_resampling(arch, mtd, data_dict[data_key], data_key)

In [25]:
#search_all_combinations()

# parameter_grid_resampling("CART", "CC", data_dict["abalone-17_vs_7-8-9-10"], "abalone-17_vs_7-8-9-10")
#parameter_grid_resampling("mlp", "CC", data_dict["abalone-17_vs_7-8-9-10"])

# Training and export

### Training resampling models

In [26]:
stopHere = False
if stopHere:
    raise SystemExit("Stopped at # Training and export")

In [20]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score
from imblearn.metrics import geometric_mean_score

def shuffle_data_and_train_and_evaluate(X, y, pipeline):
    valid_precisions = []
    valid_recalls = []

    valid_f1s = []
    valid_gmeans = []
    valid_aucs = []

    runs_target = 100
    runs_cur = 0
    seed = 0

    while runs_cur < runs_target:
        # Random Split
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, 
            test_size=0.3, 
            stratify=None, 
            random_state=seed
        )
        
        n_minority = sum(y_test == 1)
        
        if n_minority >= 10:
            # Scale
            scaler = StandardScaler()
            X_train = scaler.fit_transform(X_train)
            X_test = scaler.transform(X_test)
            
            # Train
            pipeline.fit(X_train, y_train)
            y_pred = pipeline.predict(X_test)
            y_score = pipeline.predict_proba(X_test)[:, 1] # For AUC calculation
            
            valid_precisions.append(precision_score(y_test, y_pred, pos_label=1, zero_division=0))
            valid_recalls.append(recall_score(y_test, y_pred, pos_label=1, zero_division=0))
            valid_f1s.append(f1_score(y_test, y_pred, pos_label=1, zero_division=0))
            valid_gmeans.append(geometric_mean_score(y_test, y_pred, pos_label=1))
            valid_aucs.append(roc_auc_score(y_test, y_score))
            
            runs_cur += 1
            
            if runs_cur % 10 == 0:
                print(f"Run {runs_cur}/{runs_target} completed...")

        seed += 1


    print(f"Seeds checked: {seed}")
    print(f"Average Precision: {np.mean(valid_precisions):.4f}")
    print(f"Average Recall:    {np.mean(valid_recalls):.4f}")
    print("")
    print(f"Average F1:        {np.mean(valid_f1s):.4f}")
    print(f"Standard deviation F1: {np.std(valid_f1s):.4f}")
    print(f"Average G-Mean:    {np.mean(valid_gmeans):.4f}")
    print(f"standard deviation G-Mean: {np.std(valid_gmeans):.4f}")
    print(f"Average AUC:      {np.mean(valid_aucs):.4f}")
    print(f"standard deviation AUC: {np.std(valid_aucs):.4f}")
    
    output_dict = {
        "average_precision": np.mean(valid_precisions),
        "average_recall": np.mean(valid_recalls),
        "average_f1": np.mean(valid_f1s),
        "std_f1": np.std(valid_f1s),
        "average_gmean": np.mean(valid_gmeans),
        "std_gmean": np.std(valid_gmeans),
        "average_auc": np.mean(valid_aucs),
        "std_auc": np.std(valid_aucs)
    }
    
    return output_dict

In [ ]:
import json
from datetime import datetime

# def get_all_grid_searched_pipelines():
#     pipelines_dict = {}
#     for mtd in [None, "smote", "CC"]:
#         for arch in ["CART", "mlp"]:
#             for data_key in data_dict.keys():
#                 if mtd is None:
#                     pipelines_dict[arch + "_baseline"] = create_pipeline(arch, data_level_method=None, params=None)
#                 else:
#                     pipelines_dict[arch + "_" + mtd] = parameter_grid_resampling(arch, mtd, data_dict[data_key], data_key)[0]
                    
#     return pipelines_dict


def get_all_grid_searched_pipelines():
    pipelines_dict = {}
    for mtd in [None]:
        for arch in ["mlp"]:
            for data_key in data_dict.keys():
                if mtd is None:
                    pipelines_dict[arch + "_baseline"] = create_pipeline(arch, data_level_method=None, params=None)
                else:
                    pipelines_dict[arch + "_" + mtd] = parameter_grid_resampling(arch, mtd, data_dict[data_key], data_key)[0]
                    
    return pipelines_dict
                

pipelines_dict = get_all_grid_searched_pipelines()

results_dict = {}
for name, pipeline in pipelines_dict.items():
    print(f"Training and evaluating pipeline: {name}")
    for dataset_name, (X, y, imb_ratio, imb_count) in data_dict.items():
        print(f"Dataset: {dataset_name} (Imbalance Ratio: {imb_ratio:.2f})")
        results = shuffle_data_and_train_and_evaluate(X, y, pipeline)
        results_dict[f"{name}_{dataset_name}"] = results
        print("\n" + "="*10 + "\n")
    print("\n" + "="*50 + "\n")
    

cur_date = datetime.now().strftime("%Y%m%d_%H%M%S")
with open("binary_classification_results" + cur_date + ".json", "w") as f:
    json.dump(results_dict, f, indent=4)

### Training LNR models

In [24]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score
from imblearn.metrics import geometric_mean_score

def shuffle_data_and_train_and_evaluate_lnr(X, y, arch, t_flip, n_epochs):
    valid_precisions = []
    valid_recalls = []

    valid_f1s = []
    valid_gmeans = []
    valid_aucs = []

    runs_target = 100
    runs_cur = 0
    seed = 0

    while runs_cur < runs_target:
        # Random Split
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, 
            test_size=0.3, 
            stratify=None, 
            random_state=seed
        )
        
        n_minority = sum(y_test == 1)
        
        if n_minority >= 10:
            # Scale
            scaler = StandardScaler()
            X_train = scaler.fit_transform(X_train)
            X_test = scaler.transform(X_test)
            
            # Train LNR MLP
            mlp_nlp = get_mlp_lnr(max_iter=n_epochs)
            mlp_nlp.fit(X_train, y_train)
            y_train_new = apply_lnr(mlp_nlp, X_train, y_train, t_flip) 
            
            
            # Train classifier on new labels
            pipeline = create_pipeline(arch)
            pipeline.fit(X_train, y_train_new)
            y_pred = pipeline.predict(X_test)
            y_score = pipeline.predict_proba(X_test)[:, 1] # For AUC calculation
            
            valid_precisions.append(precision_score(y_test, y_pred, pos_label=1, zero_division=0))
            valid_recalls.append(recall_score(y_test, y_pred, pos_label=1, zero_division=0))
            valid_f1s.append(f1_score(y_test, y_pred, pos_label=1, zero_division=0))
            valid_gmeans.append(geometric_mean_score(y_test, y_pred, pos_label=1))
            valid_aucs.append(roc_auc_score(y_test, y_score))
            
            runs_cur += 1
            
            if runs_cur % 10 == 0:
                print(f"Run {runs_cur}/{runs_target} completed...")

        seed += 1


    print(f"Seeds checked: {seed}")
    print(f"Average Precision: {np.mean(valid_precisions):.4f}")
    print(f"Average Recall:    {np.mean(valid_recalls):.4f}")
    print("")
    print(f"Average F1:        {np.mean(valid_f1s):.4f}")
    print(f"Standard deviation F1: {np.std(valid_f1s):.4f}")
    print(f"Average G-Mean:    {np.mean(valid_gmeans):.4f}")
    print(f"standard deviation G-Mean: {np.std(valid_gmeans):.4f}")
    print(f"Average AUC:      {np.mean(valid_aucs):.4f}")
    print(f"standard deviation AUC: {np.std(valid_aucs):.4f}")
    
    output_dict = {
        "average_precision": np.mean(valid_precisions),
        "average_recall": np.mean(valid_recalls),
        "average_f1": np.mean(valid_f1s),
        "std_f1": np.std(valid_f1s),
        "average_gmean": np.mean(valid_gmeans),
        "std_gmean": np.std(valid_gmeans),
        "average_auc": np.mean(valid_aucs),
        "std_auc": np.std(valid_aucs)
    }
    
    return output_dict

##### Train with LNR method and the optimal, found hyperparameters

In [26]:

import json
from datetime import datetime

lnr_params = {
    "mlp": {
        "abalone-17_vs_7-8-9-10": (4.0, 2050),
        "ecoli1": (3.5555555555555554, 2050),
        "glass0": (0.0, 4000),
        "vehicle1": (0.8888888888888888, 4000)
    },
    "CART": {
        "abalone-17_vs_7-8-9-10": (3.5555555555555554, 2050),
        "ecoli1": (2.2222222222222223, 2050),
        "glass0": (3.1111111111111107, 100),
        "vehicle1": (2.2222222222222223, 4000)
    }
}

results_dict = {}
for arch in ["mlp", "CART"]:
    print(f"Training with LNR: {arch}")
    for dataset_name, (X, y, imb_ratio, imb_count) in data_dict.items():
        print(f"Dataset: {dataset_name} (Imbalance Ratio: {imb_ratio:.2f})")
        results = shuffle_data_and_train_and_evaluate_lnr(X, y, arch, 
                                                        lnr_params[arch][dataset_name][0], 
                                                        lnr_params[arch][dataset_name][1])
        results_dict[f"{arch}_{dataset_name}"] = results
        print("\n" + "="*10 + "\n")
    print("\n" + "="*50 + "\n")
    

cur_date = datetime.now().strftime("%Y%m%d_%H%M%S")
with open("binary_classification_results" + cur_date + ".json", "w") as f:
    json.dump(results_dict, f, indent=4)

Training with LNR: mlp
Dataset: abalone-17_vs_7-8-9-10 (Imbalance Ratio: 39.31)
Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...
Run 40/100 completed...
Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.3752
Average Recall:    0.4038

Average F1:        0.3737
Standard deviation F1: 0.1310
Average G-Mean:    0.6027
standard deviation G-Mean: 0.1820
Average AUC:      0.9093
standard deviation AUC: 0.0797

==========

Dataset: ecoli1 (Imbalance Ratio: 3.36)
Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...
Run 40/100 completed...
Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.7629
Average Recall:    0.7903

Average F1:        0.7705
Standard deviation F1: 0.0588
Average G-Mean:    0.8536
standard deviation G-Mean: 0.0418
Average AUC:      0.9440
standard deviation AUC: 0.0272

==========

Dataset: glass0 (Imbalance Ratio: 2.06)
Run 10/100 completed...
Run 20/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 30/100 completed...
Run 40/100 completed...
Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.6112
Average Recall:    0.7907

Average F1:        0.6838
Standard deviation F1: 0.0735
Average G-Mean:    0.7708
standard deviation G-Mean: 0.0548
Average AUC:      0.8360
standard deviation AUC: 0.0504

==========

Dataset: vehicle1 (Imbalance Ratio: 2.90)
Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...
Run 40/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.6203
Average Recall:    0.7877

Average F1:        0.6917
Standard deviation F1: 0.0800
Average G-Mean:    0.8062
standard deviation G-Mean: 0.0861
Average AUC:      0.8903
standard deviation AUC: 0.0472

==========


==================================================

Training with LNR: CART
Dataset: abalone-17_vs_7-8-9-10 (Imbalance Ratio: 39.31)
Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...
Run 40/100 completed...
Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.2686
Average Recall:    0.4341

Average F1:        0.3255
Standard deviation F1: 0.0740
Average G-Mean:    0.6423
standard deviation G-Mean: 0.0892
Average AUC:      0.7018
standard deviation AUC: 0.0579

==========

Dataset: ecoli1 (Imbalance Ratio: 3.36)
Run 10/100 completed...
Run 20/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2050) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 30/100 completed...
Run 40/100 completed...
Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.6974
Average Recall:    0.8335

Average F1:        0.7546
Standard deviation F1: 0.0525
Average G-Mean:    0.8614
standard deviation G-Mean: 0.0382
Average AUC:      0.8633
standard deviation AUC: 0.0367

==========

Dataset: glass0 (Imbalance Ratio: 2.06)

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 10/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 20/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 30/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 40/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 50/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 60/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 70/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 80/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 90/100 completed...

a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
a:\6 Kod\KTH-kurser\DLFK HT25\dl_music_label_swapping\binary classification\venv_bin_class\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(

Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.6937
Average Recall:    0.7040

Average F1:        0.6904
Standard deviation F1: 0.0716
Average G-Mean:    0.7693
standard deviation G-Mean: 0.0521
Average AUC:      0.7757
standard deviation AUC: 0.0479

==========

Dataset: vehicle1 (Imbalance Ratio: 2.90)
Run 10/100 completed...
Run 20/100 completed...
Run 30/100 completed...
Run 40/100 completed...
Run 50/100 completed...
Run 60/100 completed...
Run 70/100 completed...
Run 80/100 completed...
Run 90/100 completed...
Run 100/100 completed...
Seeds checked: 100
Average Precision: 0.5049
Average Recall:    0.5712

Average F1:        0.5334
Standard deviation F1: 0.0503
Average G-Mean:    0.6770
standard deviation G-Mean: 0.0409
Average AUC:      0.6888
standard deviation AUC: 0.0352

==========


==================================================